"""Convert inline VG Wort pixels into a data-driven partial.

Reads the existing vgwort-manifest.csv (399 rows, Phase 2 of the
Quarto→Hugo migration) and produces:

  data/vgwort.yaml — keyed by Hugo content-page relative path
                     (`/track-e/kl05/units/unit01-hello-world/`).
                     Each entry carries the public_id + pixel_url +
                     min_chars threshold + author + registered_at +
                     legacy qmd_path (provenance).

After this migration runs, layouts/_partials/vgwort.html renders the
pixel from the data file on any page whose .RelPermalink matches a
key. The inline `<!-- VG Wort Zählmarke -->` block + `<img>` in each
.md is then stripped (separate function below) — the pixel travels
via the partial only.

Idempotent. Safe to re-run.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "vgwort-manifest.csv"
DATA = ROOT / "data" / "vgwort.yaml"
CONTENT = ROOT / "content"

INLINE_PIXEL_RE = re.compile(
    r"\n*<!--\s*VG Wort Zählmarke[^>]*-->\s*\n"
    r"<img\s+src=\"https://vg\d+\.met\.vgwort\.de/na/[0-9a-f]{32}\"[^>]*?/>\s*",
    re.DOTALL,
)
WRAPPER_DIV_RE = re.compile(
    r"\n*::: \{\.vgwort-pixel\}.*?:::\s*",
    re.DOTALL,
)


def qmd_to_hugo_url(qmd_rel: str) -> str:
    """Reverse the migrator's path mapping: track_e_kl05/units/unit01_hello-world.qmd
    -> /track-e/kl05/units/unit01-hello-world/."""
    p = qmd_rel.removesuffix(".qmd")
    parts = p.split("/")
    out: list[str] = []
    for c in parts:
        m = re.fullmatch(r"track_(e|gm)_kl(\d{2})", c)
        if m:
            out.extend([f"track-{m.group(1)}", f"kl{m.group(2)}"])
        else:
            # Underscore-prefixed exam-body partials were inlined into BOTH
            # the unit page and the exam wrapper during migration; the
            # wrapper kept the pixel at its current public ID.
            if c.startswith("_unit") and c.endswith("_exam_body"):
                c = c[1:].replace("_exam_body", "_exam")
            out.append(c.replace("_", "-"))
    if out and out[-1] == "index":
        out.pop()
    if not out:
        return "/"
    return "/" + "/".join(out) + "/"


def build_data_file() -> int:
    if not MANIFEST.is_file():
        print(f"manifest missing: {MANIFEST}", file=sys.stderr)
        return 1

    rows = list(csv.DictReader(MANIFEST.open(encoding="utf-8")))
    entries: list[dict] = []
    for r in rows:
        url = qmd_to_hugo_url(r["qmd_path"])
        entries.append({
            "url": url,
            "public_id": r["public_id"],
            "pixel_url": r["pixel_url"],
            "min_chars": 1800,
            "author": "S. Le Boulanger",
            "registered_at": "2026-04-30",
            "qmd_path": r["qmd_path"],
        })

    DATA.parent.mkdir(parents=True, exist_ok=True)
    with DATA.open("w", encoding="utf-8") as f:
        f.write(
            "# VG Wort Zählmarken — single source of truth for the\n"
            "# layouts/_partials/vgwort.html partial.\n"
            "#\n"
            "# Generated by _scripts/migrate_vgwort_to_data.py from\n"
            "# vgwort-manifest.csv (the Phase 2 manifest of inline pixels\n"
            "# in the original .qmd sources). Do not hand-edit; re-run\n"
            "# the migrator if the manifest changes.\n"
            "#\n"
            "# Every URL is the Hugo content-page relative path\n"
            "# (e.g. /track-e/kl05/units/unit01-hello-world/). The partial\n"
            "# matches against `.RelPermalink` minus the site basePath.\n"
            "#\n"
            "# All public_ids are registered to S. Le Boulanger via VG Wort\n"
            "# T.O.M. (one Zählmarke per work, never reused).\n\n"
        )
        yaml.dump(entries, f, sort_keys=False, allow_unicode=True)
    print(f"Wrote {len(entries)} entries to {DATA.relative_to(ROOT).as_posix()}")
    return 0


def strip_inline_pixels() -> int:
    """Remove the inline `<!-- VG Wort -->` + `<img>` from every .md.
    Idempotent — files without inline pixels are untouched."""
    n = 0
    for md in CONTENT.rglob("*.md"):
        text = md.read_text(encoding="utf-8")
        new = INLINE_PIXEL_RE.sub("\n", text)
        new = WRAPPER_DIV_RE.sub("\n", new)
        if new != text:
            md.write_text(new, encoding="utf-8")
            n += 1
    print(f"Stripped inline pixels from {n} content file(s).")
    return 0


def main() -> int:
    rc = build_data_file()
    if rc:
        return rc
    return strip_inline_pixels()


if __name__ == "__main__":
    raise SystemExit(main())
